services:
  python-app:
    container_name: s2q_speaker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - C:/xampp/htdocs/AUDIO:/src/AUDIO
    environment:
      - PYTHONUNBUFFERED=1
